"""
Prometheus Metrics Module

Exposes application metrics at /metrics for Prometheus scraping.
Tracks pipeline throughput, latency, anomaly rates, device health,
data quality, and system health.
"""

from __future__ import annotations

import threading

from prometheus_client import Counter, Gauge, Histogram, Info, start_http_server

from src.logger import get_logger

logger = get_logger("monitoring.metrics")

# ═══════════════════════════════════════════════════════════════════════════
# Pipeline Throughput Metrics
# ═══════════════════════════════════════════════════════════════════════════

READINGS_GENERATED = Counter(
    "heartbeat_readings_generated_total",
    "Total heartbeat readings generated by the data generator",
    ["customer_id"],
)

READINGS_PRODUCED = Counter(
    "heartbeat_readings_produced_total",
    "Total readings successfully sent to Kafka",
    ["customer_id"],
)

READINGS_PRODUCE_FAILED = Counter(
    "heartbeat_readings_produce_failed_total",
    "Total readings that failed to send to Kafka",
)

READINGS_CONSUMED = Counter(
    "heartbeat_readings_consumed_total",
    "Total readings consumed from Kafka",
    ["customer_id"],
)

READINGS_PERSISTED = Counter(
    "heartbeat_readings_persisted_total",
    "Total readings written to PostgreSQL",
    ["customer_id"],
)

READINGS_REJECTED = Counter(
    "heartbeat_readings_rejected_total",
    "Total readings rejected by validation",
    ["reason"],
)

# ═══════════════════════════════════════════════════════════════════════════
# Edge Case 1 – Heartbeat Delay Detection
# ═══════════════════════════════════════════════════════════════════════════

DEVICE_LAST_SEEN = Gauge(
    "heartbeat_device_last_seen_timestamp",
    "Unix timestamp of the last reading received from this device/customer",
    ["customer_id"],
)

DEVICE_HEARTBEAT_DELAY_SECONDS = Gauge(
    "heartbeat_device_delay_seconds",
    "Seconds since last heartbeat from device (updated each poll cycle)",
    ["customer_id"],
)

DEVICE_HEARTBEAT_DELAY_ALERT = Counter(
    "heartbeat_device_delay_alerts_total",
    "Number of times a device exceeded the heartbeat delay threshold",
    ["customer_id"],
)

# ═══════════════════════════════════════════════════════════════════════════
# Edge Case 2 – Device Failure Detection
# ═══════════════════════════════════════════════════════════════════════════

DEVICE_STATUS = Gauge(
    "heartbeat_device_status",
    "Device status: 1 = ACTIVE, 0 = INACTIVE/FAILED",
    ["customer_id"],
)

DEVICE_FAILURE_TOTAL = Counter(
    "heartbeat_device_failures_total",
    "Number of times a device was detected as failed (no data past threshold)",
    ["customer_id"],
)

DEVICE_CONSECUTIVE_ERRORS = Gauge(
    "heartbeat_device_consecutive_errors",
    "Consecutive error count per device",
    ["customer_id"],
)

# ═══════════════════════════════════════════════════════════════════════════
# Edge Case 3 – Sudden Spike Detection
# ═══════════════════════════════════════════════════════════════════════════

HEART_RATE_VALUE = Gauge(
    "heartbeat_heart_rate_bpm",
    "Current heart rate reading in bpm",
    ["customer_id"],
)

HEART_RATE_HISTOGRAM = Histogram(
    "heartbeat_heart_rate_distribution",
    "Distribution of heart rate values",
    ["customer_id"],
    buckets=[30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 150, 180, 200, 250],
)

SPIKE_DETECTED = Counter(
    "heartbeat_spike_detected_total",
    "Number of sudden reading spikes detected (delta > threshold between consecutive reads)",
    ["customer_id", "direction"],  # direction: 'up' or 'down'
)

# ═══════════════════════════════════════════════════════════════════════════
# Edge Case 4 – Anomaly Tracking
# ═══════════════════════════════════════════════════════════════════════════

ANOMALIES_DETECTED = Counter(
    "heartbeat_anomalies_detected_total",
    "Total anomalies detected by type",
    ["customer_id", "anomaly_type"],
)

ANOMALY_RATE = Gauge(
    "heartbeat_anomaly_rate_percent",
    "Rolling anomaly rate as a percentage of total readings",
)

# ═══════════════════════════════════════════════════════════════════════════
# Edge Case 5 – Data Quality
# ═══════════════════════════════════════════════════════════════════════════

DATA_QUALITY_VALID = Counter(
    "heartbeat_data_quality_valid_total",
    "Readings that passed all validation checks",
)

DATA_QUALITY_INVALID = Counter(
    "heartbeat_data_quality_invalid_total",
    "Readings that failed validation checks",
    ["validation_error"],
)

DATA_QUALITY_SCORE = Gauge(
    "heartbeat_data_quality_score_percent",
    "Rolling data quality score (valid / total * 100)",
)

# ═══════════════════════════════════════════════════════════════════════════
# DLQ Metrics
# ═══════════════════════════════════════════════════════════════════════════

DLQ_MESSAGES_TOTAL = Counter(
    "heartbeat_dlq_messages_total",
    "Total messages sent to the Dead Letter Queue",
    ["reason"],
)

DLQ_MESSAGES_CURRENT = Gauge(
    "heartbeat_dlq_messages_current",
    "Approximate current messages sitting in the DLQ topic",
)

DLQ_RETRIES_TOTAL = Counter(
    "heartbeat_dlq_retries_total",
    "Total retry attempts from the DLQ",
)

DLQ_RETRY_SUCCESS = Counter(
    "heartbeat_dlq_retry_success_total",
    "Successful DLQ reprocessing count",
)

# ═══════════════════════════════════════════════════════════════════════════
# System Health Metrics
# ═══════════════════════════════════════════════════════════════════════════

KAFKA_PRODUCER_CONNECTED = Gauge(
    "heartbeat_kafka_producer_connected",
    "Whether the Kafka producer is connected (1) or not (0)",
)

KAFKA_CONSUMER_CONNECTED = Gauge(
    "heartbeat_kafka_consumer_connected",
    "Whether the Kafka consumer is connected (1) or not (0)",
)

DATABASE_CONNECTED = Gauge(
    "heartbeat_database_connected",
    "Whether the database pool is connected (1) or not (0)",
)

PIPELINE_UPTIME_SECONDS = Gauge(
    "heartbeat_pipeline_uptime_seconds",
    "Seconds since the pipeline started",
)

PROCESSING_LATENCY = Histogram(
    "heartbeat_processing_latency_seconds",
    "End-to-end processing latency from generation to DB insert",
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
)

KAFKA_PRODUCE_LATENCY = Histogram(
    "heartbeat_kafka_produce_latency_seconds",
    "Time to produce a message to Kafka",
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1],
)

DB_INSERT_LATENCY = Histogram(
    "heartbeat_db_insert_latency_seconds",
    "Time to insert a batch into PostgreSQL",
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5],
)

CONSUMER_LAG = Gauge(
    "heartbeat_consumer_lag_messages",
    "Estimated consumer lag (messages behind latest offset)",
)

# ═══════════════════════════════════════════════════════════════════════════
# Reporting Metrics (tracked for daily/weekly summaries)
# ═══════════════════════════════════════════════════════════════════════════

REPORT_READINGS_DAILY = Gauge(
    "heartbeat_report_readings_daily",
    "Total readings processed in the current day",
)

REPORT_READINGS_WEEKLY = Gauge(
    "heartbeat_report_readings_weekly",
    "Total readings processed in the current week",
)

REPORT_ANOMALIES_DAILY = Gauge(
    "heartbeat_report_anomalies_daily",
    "Anomalies detected today",
)

REPORT_ANOMALIES_WEEKLY = Gauge(
    "heartbeat_report_anomalies_weekly",
    "Anomalies detected this week",
)

REPORT_READINGS_MONTHLY = Gauge(
    "heartbeat_report_readings_monthly",
    "Total readings processed in the current month",
)

REPORT_ANOMALIES_MONTHLY = Gauge(
    "heartbeat_report_anomalies_monthly",
    "Anomalies detected this month",
)

# ═══════════════════════════════════════════════════════════════════════════
# Pipeline Info
# ═══════════════════════════════════════════════════════════════════════════

PIPELINE_INFO = Info(
    "heartbeat_pipeline",
    "Heartbeat pipeline build information",
)

# ═══════════════════════════════════════════════════════════════════════════
# Data Quality Framework Metrics
# ═══════════════════════════════════════════════════════════════════════════

DQ_VALIDATIONS_TOTAL = Counter(
    "heartbeat_dq_validations_total",
    "Total DQ row validations by result (pass/fail)",
    ["result"],
)

DQ_RULE_FAILURES = Counter(
    "heartbeat_dq_rule_failures_total",
    "DQ rule failures by rule name and dimension",
    ["rule_name", "dimension"],
)

DQ_OVERALL_SCORE = Gauge(
    "heartbeat_dq_overall_score_percent",
    "Weighted overall data quality score (0-100)",
)

DQ_COMPLETENESS_SCORE = Gauge(
    "heartbeat_dq_completeness_score_percent",
    "Completeness dimension score (0-100)",
)

DQ_VALIDITY_SCORE = Gauge(
    "heartbeat_dq_validity_score_percent",
    "Validity dimension score (0-100)",
)

DQ_CONSISTENCY_SCORE = Gauge(
    "heartbeat_dq_consistency_score_percent",
    "Consistency dimension score (0-100)",
)

DQ_TIMELINESS_SCORE = Gauge(
    "heartbeat_dq_timeliness_score_percent",
    "Timeliness dimension score (0-100)",
)

DQ_BATCH_DURATION = Histogram(
    "heartbeat_dq_batch_validation_seconds",
    "Time to validate a batch of readings with the DQ engine",
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5],
)

DQ_ROWS_PASSED = Counter(
    "heartbeat_dq_rows_passed_total",
    "Rows that passed all critical quality checks",
)

DQ_ROWS_FAILED = Counter(
    "heartbeat_dq_rows_failed_total",
    "Rows that failed quality checks (routed to DLQ) by dimension",
    ["dimension"],
)

DQ_QUARANTINED_TOTAL = Counter(
    "heartbeat_dq_quarantined_total",
    "Rows permanently quarantined (non-retryable DQ failures)",
)

DQ_CIRCUIT_BREAKER_TRIPS = Counter(
    "heartbeat_dq_circuit_breaker_trips_total",
    "Number of times the DQ circuit breaker was tripped (batch failure rate exceeded threshold)",
)

# ═══════════════════════════════════════════════════════════════════════════
# Metrics Server
# ═══════════════════════════════════════════════════════════════════════════

_metrics_server_started = False
_server_lock = threading.Lock()


def start_metrics_server(port: int = 8000) -> None:
    """
    Start the Prometheus metrics HTTP server on the given port.

    Idempotent – calling multiple times is safe.

    Args:
        port: TCP port to expose /metrics endpoint.
    """
    global _metrics_server_started
    with _server_lock:
        if _metrics_server_started:
            return
        start_http_server(port)
        _metrics_server_started = True
        logger.info("Prometheus metrics server started on port %d", port)

        PIPELINE_INFO.info(
            {
                "version": "1.0.0",
                "component": "heartbeat-pipeline",
                "metrics_port": str(port),
            }
        )
